services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: vitegourmand_php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: vitegourmand_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    container_name: vitegourmand_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vite_gourmand
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

  mongodb:
    image: mongo:8
    container_name: vitegourmand_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  database_data:
  mongodb_data:
