services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.4
    container_name: vite_gourmand_mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: vite_gourmand
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app

    ports:
      - "3307:3306"

    volumes:
      - database:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -proot --silent"
        ]
      timeout: 5s
      retries: 10
      start_period: 30s
###< doctrine/doctrine-bundle ###

  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi9-slim
    container_name: vite_gourmand_mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongodb:/data/db

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: vite_gourmand_php
    restart: unless-stopped
    working_dir: /var/www/app

    volumes:
      - ./:/var/www/app

    depends_on:
      database:
        condition: service_healthy
      mongodb:
        condition: service_started

volumes:
###> doctrine/doctrine-bundle ###
  database:
###< doctrine/doctrine-bundle ###
  mongodb: