services:
  database:
    image: mysql:8.4
    container_name: vite_gourmand_mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: vite_gourmand
      MYSQL_ROOT_PASSWORD: Admin/2026/ecf
      MYSQL_USER: app
      MYSQL_PASSWORD: Admin/2026/ecf

    volumes:
      - database:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD --silent"
        ]
      timeout: 5s
      retries: 10
      start_period: 30s

  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi9-slim
    container_name: vite_gourmand_mongodb
    restart: unless-stopped

    volumes:
      - mongodb:/data/db

  mailer:
    image: axllent/mailpit
    container_name: vite_gourmand_mailpit
    restart: unless-stopped

    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "1"
      MP_SMTP_AUTH_ALLOW_INSECURE: "1"

    ports:
      - "127.0.0.1:8025:8025"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: vite_gourmand_php
    restart: unless-stopped
    working_dir: /var/www/app

    environment:
      DATABASE_URL: "mysql://app:Admin%%2F2026%%2Fecf@database:3306/vite_gourmand?serverVersion=8.4.0&charset=utf8mb4"
      APP_MONGODB_URL: "mongodb://mongodb:27017"
      APP_MONGODB_DB: "vite_gourmand_stats"
      MAILER_DSN: "smtp://mailer:1025"

    depends_on:
      database:
        condition: service_healthy
      mongodb:
        condition: service_started
      mailer:
        condition: service_started

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile

    container_name: vite_gourmand_nginx
    restart: unless-stopped

    ports:
      - "8080:80"

    depends_on:
      php:
        condition: service_started

volumes:
  database:
  mongodb: