<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOjrS0Yc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOjrS0Yc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOjrS0Yc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOjrS0Yc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOjrS0Yc\App_KernelDevDebugContainer([
    'container.build_hash' => 'OjrS0Yc',
    'container.build_id' => '80cd9fa3',
    'container.build_time' => 1783283016,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOjrS0Yc');
