<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIcOyibD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIcOyibD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIcOyibD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIcOyibD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIcOyibD\App_KernelDevDebugContainer([
    'container.build_hash' => 'IcOyibD',
    'container.build_id' => 'c351f5ac',
    'container.build_time' => 1783176200,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIcOyibD');
